### PR TITLE
readme update for memory usage of Verb SRL in pipeline (close #656); ChunkerTrain bug fixed and model updated (close #685)

### LINKED ISSUE #656: Pipeline SRL Verb Fails Weirdly
I'm trying to use pipeline to process some raw text and output a TextAnnotation with `verb SRL`. This is kind of urgent since I'm deploying my package as an online demo and the demo paper is due on 6/1. *Originally I was using curator, but the curator failed frequently (not always). Then I switched to pipeline but my pipeline always fails.* Any suggestions to workaround this would be great. @danyaljj @mssammon @HornHehhf  All I need is`verb SRL`.

I checkout the latest version of cogcomp-nlp. Here's the main function I use:

```
public static void main(String[] args) throws Exception{
        String text = "Helicopters patrol the temporary no-fly zone around New Jersey's MetLife Stadium Sunday, with F-16s based in Atlantic City ready to be scrambled if an unauthorized aircraft does enter the restricted airspace.";
        ResourceManager userConfig = new ResourceManager("pipeline/config/pipeline-config.properties");
        AnnotatorService pipeline = PipelineFactory.buildPipeline(userConfig);
        TextAnnotation ta = pipeline.createAnnotatedTextAnnotation( "", "", text );
        System.out.println();
    }
```

I got this error:
```
Connected to the target VM, address: '127.0.0.1:39575', transport: 'socket'
14:11:02 INFO  DepAnnotator:66 - Loading struct-perceptron-auto-20iter.model into temp file: tmp345673.model
14:11:03 INFO  SLModel:88 - Load trained Models.....
14:11:05 INFO  SLModel:97 - Load Model complete!
14:11:05 INFO  LabeledChuLiuEdmondsDecoder:72 - Loading cached PoS-to-dep dictionary from deprels.dict
14:11:06 ERROR BasicAnnotatorService:403 - The annotator for view SRL_VERB failed. Skipping the view . . . 
14:11:06 ERROR BasicAnnotatorService:403 - The annotator for view DEPENDENCY failed. Skipping the view . . . 
edu.illinois.cs.cogcomp.annotation.AnnotatorException: View 'NER_CONLL' cannot be provided by this AnnotatorService.
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:308)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:313)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:400)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:378)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:193)
	at edu.illinois.cs.cogcomp.pipeline.main.test.main(test.java:12)
edu.illinois.cs.cogcomp.annotation.AnnotatorException: View 'SHALLOW_PARSE' cannot be provided by this AnnotatorService.
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:308)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addView(BasicAnnotatorService.java:313)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.addViewsAndCache(BasicAnnotatorService.java:400)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:378)
	at edu.illinois.cs.cogcomp.annotation.BasicAnnotatorService.createAnnotatedTextAnnotation(BasicAnnotatorService.java:193)
	at edu.illinois.cs.cogcomp.pipeline.main.test.main(test.java:12)

Disconnected from the target VM, address: '127.0.0.1:39575', transport: 'socket'

Process finished with exit code 0

```

### LINKED ISSUE #685: ChunkerTrain fails with auto selection of training rounds using a separate development set
When discussing [pull req 682](https://github.com/CogComp/cogcomp-nlp/pull/682) with Christos, I tested ChunkerTrain for something else, but I found that it's now failing.
Here's the result I got standing at the commit: 99971bdbae607b3a53d90386eb92d9ec986fb505 This is a commit before any of my recent changes to chunker.
```
Iteration number : 1. F1 score on devset: 0.9995071926407434
Iteration number : 2. F1 score on devset: 0.9995071926407434
Iteration number : 3. F1 score on devset: 0.9995071926407434
Iteration number : 4. F1 score on devset: 0.9995071926407434
Iteration number : 5. F1 score on devset: 0.9995071926407434
```
(See the F1 on dev is not changing at all, which is abnormal.)

The benchmark test is still good:
```
With Gold POS
 Label   Precision Recall   F1   LCount PCount
----------------------------------------------
ADJP        76.633 69.635 72.967    438    398
ADVP        81.862 79.215 80.516    866    838
CONJP       45.455 55.556 50.000      9     11
INTJ        50.000 50.000 50.000      2      2
LST          0.000  0.000  0.000      5      1
NP          94.106 93.962 94.034  12422  12403
PP          96.770 97.776 97.270   4811   4861
PRT         72.072 75.472 73.733    106    111
SBAR        88.280 87.290 87.782    535    529
UCP          0.000  0.000  0.000      0      5
VP          93.416 93.517 93.466   4658   4663
----------------------------------------------
O            0.000  0.000  0.000   1244   1274
----------------------------------------------
Overall     93.510 93.393 93.451  23852  23822
Accuracy    88.763   -      -      -     25096

With NO POS
 Label   Precision Recall   F1   LCount PCount
----------------------------------------------
ADJP        78.608 69.635 73.850    438    388
ADVP        80.427 78.291 79.345    866    843
CONJP       45.455 55.556 50.000      9     11
INTJ       100.000 50.000 66.667      2      1
LST          0.000  0.000  0.000      5      0
NP          94.193 94.019 94.106  12422  12399
PP          96.656 97.942 97.295   4811   4875
PRT         60.417 82.075 69.600    106    144
SBAR        86.813 88.598 87.697    535    546
UCP          0.000  0.000  0.000      0      4
VP          94.105 94.246 94.176   4658   4665
----------------------------------------------
O            0.000  0.000  0.000   1231   1207
----------------------------------------------
Overall     93.529 93.623 93.576  23852  23876
Accuracy    89.028   -      -      -     25083
```
(The numbers are exactly the same as `chunker/doc/performance.txt`)

**I guess maybe the changes in other parts of the repository failed ChunkerTrain** since ChunkerTrain itself hasn't been updated at all since 11/18/2016 (see this [log](https://github.com/CogComp/cogcomp-nlp/commits/master/chunker/src/main/java/edu/illinois/cs/cogcomp/chunker/main/ChunkerTrain.java)).

### PR DESCRIPTION
**Pull request by qiangning**
After investigation of the memory usage of Verb SRL in our pipeline, I suggest that we close #656  with a few notes added in README.

### CODE REVIEW

**Comment by qiangning** [comment]
Note: I'm working on two issues and they got merged into this single PR.

The first commit of `readme update for memory usage...` is to close #656. This is straightforward: I'm adding a few lines in the readme file of `pipeline` to clarify the memory usage of VerbSRL.

The other three commits are to close #685. I fixed the bug of [ChunkerTrain](https://github.com/CogComp/cogcomp-nlp/blob/master/chunker/src/main/java/edu/illinois/cs/cogcomp/chunker/main/ChunkerTrain.java) that it wrongly loads pretrained models when training a new one. I then retrained the model and found that the performance got slightly improved. So I deployed the new model to [here](http://cogcomp.org/m2repo/edu/illinois/cs/cogcomp/illinois-chunker-model/4.0.12/) and changed the code accordingly.

**Comment by mssammon** [comment]
@qiangning looks like CI build is failing -- please take a look.

**Comment by qiangning** [comment]
It should be that the mvn test failed. I'm working on it.

**Comment by cogcomp-dev** [comment]
@qiangning CI test is failing because chunker output has changed, and the test diffs it with a reference output. Please update the test files and this should be good to go.

**Comment by qiangning** [comment]
Thanks. Yes, I found it. Plan to work on it tonight.

**Comment by qiangning** [comment]
All the test has passed. If no objections, I'll merge it sometime late tonight.

**Pull request merged**
